print("--Operator Matematika--")
print("Tambah (+)", 10+2)
print("Kali (*)", 12*2)
print("Bagi (/)", 8/5)
print("Kurang (-)", 14-1)
print("Pangkat (+)", 2**2)
print("Mod (%)", 6%2)

print("--Operator Pembanding--")
print("Sama Dengan (==)")
print("Lebih Besar (>)")
print("Lebih Kecil (<)")
print("Lebih Besar Sama Dengan (>=)")
print("Lebih Kecil Sama Dengan(<=)")
print("Tidak Sama Dengan(!=)")

print("--Operator Logika--")
print("Not (not=Bukan)")
print("And (and=Semua Kondisi Terpenuhi)")
print("Or (or=Salah Satu Kondisi Terpenuhi)")